version: "2"

networks:
  network_s5r:
    driver: host

services:

  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - "8080:15672"
      - "5672:5672"

  strategy-x:
    build:
      context: .
    command: sh wait_to_start.sh
    environment:
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://rabbitmq:15672) = 200 ]
      - WAIT_SLEEP=2
      - WAIT_LOOPS=20
      - WAIT_START_CMD=yarn run start:dev
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - SAMMLER_JOBS_SERVICE_URI=http://jobs-service:3003
    volumes:
      - ./:/home
    links:
      - rabbitmq
