version: "2"

networks:
  network_s5r:
    driver: host

services:

  db:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - "8080:15672"
      - "5672:5672"

  scheduler:
    build:
      context: ./services/scheduler
    command: sh wait_to_start.sh
    environment:
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://rabbitmq:15672) = 200 ]
      - WAIT_START_CMD=yarn run start:dev
      - WAIT_SLEEP=2
      - WAIT_LOOPS=20
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    links:
      - db
      - rabbitmq

  strategy-x:
    build:
      context: ./services/strategy-x
    command: sh wait_to_start.sh
    environment:
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://rabbitmq:15672) = 200 ]
      - WAIT_SLEEP=2
      - WAIT_LOOPS=20
      - WAIT_START_CMD=yarn run start:dev
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - SAMMLER_JOBS_SERVICE_URI=http://jobs-service:3003
    volumes:
      - ./:/home
    links:
      - db
      - rabbitmq
      - jobs-service
      - log-service

  jobs-service:
    build:
      context: ./node_modules/sammler-jobs-service
#    command: sh wait_to_start.sh
    environment:
#      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://db:27017) = 200 ]
#      - WAIT_START_CMD=yarn run start
#      - WAIT_SLEEP=2
#      - WAIT_LOOPS=20
      - PORT=3003
      - SAMMLER_DB_URI_JOBS=mongodb://db:27017/jobs
    links:
      - db

  log-service:
    build:
      context: ./node_modules/sammler-log-service
#    command: sh wait_to_start.sh
    environment:
#      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://db:27017) = 200 ]
#      - WAIT_START_CMD=yarn run start
#      - WAIT_SLEEP=2
#      - WAIT_LOOPS=20
      - PORT=3004
      - SAMMLER_DB_URI_LOGS=mongodb://db:27017/logs
    links:
      - db
      - rabbitmq
