version: "2"

networks:
  network_s5r:
    driver: host

services:

#  db:
#    image: mongo
#    ports:
#      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.6.6-management
    ports:
      - "8080:15672"
      - "5672:5672"

  scheduler:
    build:
      context: ./services/scheduler
    environment:
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    links:
      - rabbitmq

  strategy-x:
    build:
      context: ./services/strategy-x
    command: sh wait_to_start.sh
    environment:
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://rabbitmq:15672) = 200 ]
      - WAIT_START_CMD=yarn run start
      - WAIT_SLEEP=2
      - WAIT_LOOPS=20
      - SAMMLER_RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    links:
      - rabbitmq
#      - db
